default: &DEFAULT
  name: 'fno_base'
  net: &DEFAULT_NET
    name: 'FNOVertex'
    n_modes_height: 16                    
    n_modes_width: 16
    hidden_channels: 128                  
    in_channels: 3
    out_channels: 1
    lifting_channels: 256
    projection_channels: 256
    n_layers: 4                           
    domain_padding: null                  
    domain_padding_mode: null             
    skip: 'soft-gating'
    implementation: 'factorized'          
    use_channel_mlp: 0                    
    channel_mlp_dropout: 0
    channel_mlp_expansion: 0.5
    separable: False
    factorization: None
    rank: 1.0
    fixed_rank_modes: None
    joint_factorization: False
    fno_block_precision: 'full'           
    stabilizer: None                      
    positional_embedding: grid
    dtype: float32


  ema:
    update_after_step: None  # Start updating EMA after this number of steps
    update_every: 1  # Update EMA every 'n' steps
    beta: 0.995  # EMA smoothing factor (closer to 1 means smoother updates)

  data: &DEFAULT_DATA
    dataset_size: 1000
    average_sequence_length: 1000
    n_batches_per_epoch: 5000

    height: 100
    width: 100
    seed: 666

    use_cloth: 1
    use_fluid: 0
    use_diffusion: 0
    use_poisson: 0

    noise_acc: 0
    noise_grad: 0


  # Optimizer
  opt: &DEFAULT_OPT
    lr: 0.001  # Learning rate for the optimizer
    batch_size: 10  # Batch size for training
    n_epochs: 100  # Number of training epochs
    clip_grad_norm: null  # Gradient norm clipping threshold
    clip_grad_value: null  # Gradient value clipping threshold
    optimizer: adamw
    cuda: 1
    plot: 0
    warmup: 5
    initial_warmup: 30
    reset_loss_limit: 1000
    save_mesh: 0
    i_save: 20
    L_shear_bend_version: 1
    seed: 666


  cloth: &DEFAULT_CLOTH
    use_f_ext: 0
    max_stretching: 1000  # Maximum stretching parameter for cloth
    min_stretching: 100  # Minimum stretching parameter for cloth
    max_shearing: 100  # Maximum shearing parameter for cloth
    min_shearing: 1  # Minimum shearing parameter for cloth
    max_bending: 10  # Maximum bending parameter for cloth
    min_bending: 0.01  # Minimum bending parameter for cloth
    a_ext: 1  # External acceleration (gravitational constant)
    min_a_ext: null  # Minimum gravitational constant (defaults to a_ext if not set)
    g: 0.125  # Gravitational constant (deprecated, prefer a_ext)
    L_0: 1  # Rest length of cloth grid edges
    dt: 1  # Timestep for cloth simulation integrator
    repulsive:
      k: 0
      resolution: 32
      thres: 0.5
    # Load parameters
    l_stretching: null  # Load stretching parameter of cloth
    l_shearing: null  # Load shearing parameter of cloth
    l_bending: null  # Load bending parameter of cloth
    l_g: null  # Load gravitational constant
    l_L_0: null  # Load rest length of cloth grid edges
    l_dt: 1  # Load timestep of cloth simulation integrator
    load_date_time: null  # Date and time of the run to load
    load_index: null  # Index of the run to load
    load_optimizer: false  # Whether to load the state of the optimizer
    load_latest: false  # Load the latest version for training (overrides date_time and index)


  # Weights and biases
  wandb: &DEFAULT_WANDB
    root_dir: './'
    log: false
    group: 'fno'

  distributed:
    use_distributed: False
    wireup_info: 'mpi'
    wireup_store: 'tcp'
    model_parallel_size: 2

  inference: &DEFAULT_INFERENCE
    load_date_time: "??"
    load_index: null
    visualize_3d: 1
    visualize_scaling: 0
    visualize_grads: 0
    save_obj: 0
    postfix: "a"
    renderer: "Nvdiffrast"          # Nvdiffrast / PyTorch3D
    height: 100
    width: 100
    iterations_per_timestep: 10
    device: cuda
    material:
      stretching: 1000
      shearing: 8
      bending: 0.5



    rollout: &DEFAULT_ROLLOUT
      n_frames: 300
      save_render_fnopt: 1
      save_render_3d: 0
      using_handle_traj: 0
      save_acc_heatmap: 1
      wind_density: 0.0
      save_npy: 1
      evaluate: 0
      framerate: 60
      show_handle_points: 1
      log_repulsive: 0
      json: ["sft/scenes/S1_res32.json"]


      input_data:
        motion_code: debug    # [debug, regular, full, fancy]
        mode: with_gt       # [arbitrary, with_gt]
        obj_code: square_1024
        speed: 1

  ablation:
    optimizer:
      opt_type: lbfgs    # adam, gd, lbfgs
      lr: 0.01
      momentum: 0.9
      lbfgs_hist: 10
      lbfgs_eps: 1e-12
      max_step_norm: None




rollout_handle_full: &rollout_handle_full
  <<: *DEFAULT_ROLLOUT
  json: ["configs/scenes/S_MGNRP_res32.json"]
  save_render: 1
  save_acc_heatmap: 0
  save_render_3d: 0
  using_handle_traj: 1
  input_data:
    motion_code: full
    mode: arbitrary       # [arbitrary, with_gt]
    obj_code: square_1024
    speed: 1

rollout_handle_regular: &rollout_handle_regular
  <<: *DEFAULT_ROLLOUT
  json: ["configs/scenes/S_MGNRP_res32.json"]
  save_render: 1
  save_acc_heatmap: 0
  save_render_3d: 0
  using_handle_traj: 1
  input_data:
    motion_code: regular
    mode: arbitrary       # [arbitrary, with_gt]
    obj_code: square_1024
    speed: 1


rollout_handle_fancy: &rollout_handle_fancy
  <<: *DEFAULT_ROLLOUT
  json: ["configs/scenes/S_MGNRP_res32.json"]
  save_render: 1
  save_acc_heatmap: 0
  save_render_3d: 0
  using_handle_traj: 1
  input_data:
    motion_code: fancy
    mode: arbitrary       # [arbitrary, with_gt]
    obj_code: square_1024
    speed: 1

rollout_handle_debug: &rollout_handle_debug
  <<: *DEFAULT_ROLLOUT
  json: ["configs/scenes/S_MGNRP_res32.json"]
#  json: ["configs/scenes/S_MGNRP_res64.json"]
#  json: ["configs/scenes/S_MGNRP_64x32.json"]
#  json: ["configs/scenes/S_MGNRP_48x32.json"]
#  json: ["configs/scenes/S_MGNRP_32x64.json"]
#  json: ["configs/scenes/S_MGNRP_32x32.json"]
#  json: ["configs/scenes/S_MGNRP_res32_bc_corner_center.json"]
#  json: ["configs/scenes/S_MGNRP_res32_bc_single_corner.json"]
  save_render: 1
  save_acc_heatmap: 0
  save_render_3d: 0
  save_render_fnopt: 1
  using_handle_traj: 1
  input_data:
    motion_code: xy_v2
    mode: with_gt       # [arbitrary, with_gt]
    obj_code: square_1024
    speed: 1



rollout_handle_eval: &rollout_handle_eval
  <<: *DEFAULT_ROLLOUT
  json: ["configs/scenes/S_MGNRP_res32.json"]
  save_render: 0
  save_acc_heatmap: 0
  save_render_3d: 1
  using_handle_traj: 1
  evaluate: 1
  input_data:
    motion_code: eval
    mode: with_gt       # [arbitrary, with_gt]
    obj_code: square_1024
    speed: 1


e11: &e11
  <<: *DEFAULT
  name: '0610_e11_fno_res32_scale_feature_layer=2'

  net: &net_e11
    <<: *DEFAULT_NET
    n_modes_height: 8                    # try smaller
    n_modes_width: 8
    hidden_channels: 64                  # try different
    projection_channels: 64
    scale_feature_layer: 2
  opt:
    <<: *DEFAULT_OPT
    clip_grad_norm: 1
  
  cloth:
    <<: *DEFAULT_CLOTH
  
  data:
    <<: *DEFAULT_DATA
    height: 32
    width: 32

  inference: &inference_e11
    <<: *DEFAULT_INFERENCE
    load_date_time: "??" # replace with the trained model
    postfix: "e11"
    iterations_per_timestep: 10
    average_sequence_length: 500
    height: 100
    width: 100

    rollout:
      <<: *rollout_handle_eval



handle_e11:
  <<: *e11
  inference:
    <<: *inference_e11
    rollout:
      <<: *rollout_handle_full
      wind_density: 1.0


local: &local
  <<: *e11
  net:
    <<: *net_e11

  opt:
    <<: *DEFAULT_OPT
    batch_size: 3
    cuda: 0
    plot: 0

  # Weights and biases
  wandb:
    <<: *DEFAULT_WANDB
    log: false

  inference:
    <<: *inference_e11
    renderer: "PyTorch3D"
    device: cpu
    visualize_3d: 1
    visualize_scaling: 0
    visualize_grads: 0
    iterations_per_timestep: 10
    height: 32
    width: 32
    load_index: null
    material:
      stretching: 1000
      shearing: 8
      bending: 0.01
    rollout:
      <<: *rollout_handle_debug
      save_npy: 1
      wind_density: 1
      n_frames: 500
      evaluate: 0
