default: &DEFAULT
  name: 'meshgraphnets_base'
  net: &DEFAULT_NET
    name: 'MeshGraphNets2'
    message_passing_steps: 15
    node_input_size: 12
    edge_input_size: 4
    dtype: float32

  ema:
    update_after_step: None  # Start updating EMA after this number of steps
    update_every: 1  # Update EMA every 'n' steps
    beta: 0.995  # EMA smoothing factor (closer to 1 means smoother updates)

  data: &DEFAULT_DATA
    dataset_size: 1000
    average_sequence_length: 1000
    n_batches_per_epoch: 501  # default is 5000 or 501?
    height: 100
    width: 100
    seed: 666

    use_cloth: 1
    use_fluid: 0
    use_diffusion: 0
    use_poisson: 0

  # Optimizer
  opt: &DEFAULT_OPT
    lr: 0.001  # Learning rate for the optimizer
    batch_size: 3  # Batch size for training
    n_epochs: 100  # Number of training epochs
    clip_grad_norm: null  # Gradient norm clipping threshold
    clip_grad_value: null  # Gradient value clipping threshold
    cuda: 1
    plot: 0
    save_mesh: 1
    i_save: 1
    L_shear_bend_version: 1
    seed: 666
    optimizer: adamw


  cloth: &DEFAULT_CLOTH
    use_f_ext: 0
    max_stretching: 1000  # Maximum stretching parameter for cloth
    min_stretching: 100  # Minimum stretching parameter for cloth
    max_shearing: 100  # Maximum shearing parameter for cloth
    min_shearing: 1  # Minimum shearing parameter for cloth
    max_bending: 10  # Maximum bending parameter for cloth
    min_bending: 0.01  # Minimum bending parameter for cloth
    repulsive: &DEFAULT_repulsive
      k: 0
      resolution: 32  # Repulsive force between cloth vertices

    a_ext: 1  # External acceleration (gravitational constant)
    min_a_ext: null  # Minimum gravitational constant (defaults to a_ext if not set)
    g: 0.125  # Gravitational constant (deprecated, prefer a_ext)
    L_0: 1  # Rest length of cloth grid edges
    dt: 1  # Timestep for cloth simulation integrator

    # Load parameters
    l_stretching: null  # Load stretching parameter of cloth
    l_shearing: null  # Load shearing parameter of cloth
    l_bending: null  # Load bending parameter of cloth
    l_g: null  # Load gravitational constant
    l_L_0: null  # Load rest length of cloth grid edges
    l_dt: 1  # Load timestep of cloth simulation integrator
    load_date_time: null  # Date and time of the run to load
    load_index: null  # Index of the run to load
    load_optimizer: false  # Whether to load the state of the optimizer
    load_latest: false  # Load the latest version for training (overrides date_time and index)

  # Weights and biases
  wandb: &DEFAULT_WANDB
    root_dir: './'
    log: true
    group: 'meshgraphnets'

  distributed:
    use_distributed: False
    wireup_info: 'mpi'
    wireup_store: 'tcp'
    model_parallel_size: 1

  inference: &DEFAULT_INFERENCE
    load_date_time: "???"
    load_index: null
    save_obj: 0
    visualize_scaling: 0
    visualize_grads: 0
    postfix: "a"
    renderer: "Nvdiffrast"          # Nvdiffrast / PyTorch3D
    framerate: 50
    average_sequence_length: 100
    iterations_per_timestep: 10
    height: 100
    width: 100
    cuda: 1

    material:
      stretching: 1000
      shearing: 10
      bending: 10
    sft: &DEFAULT_SFT
#      json: [ "scenes/R1.json", "scenes/R2.json","scenes/R3.json","scenes/R4.json","scenes/R5.json","scenes/R6.json","scenes/R7.json","scenes/R8.json","scenes/R9.json","scenes/S1_res32.json","scenes/S2_res32.json","scenes/S3_res32.json","scenes/S4_res32.json" ]
#      json: ["sft/scenes/S1_res32.json", "scenes/S2_res32.json", "scenes/S3_res32.json", "scenes/S4_res32.json"]
      json: ["sft/scenes/S1_res32.json"]
      evaluate: 1
      optimize_uv: 0
      debug: 1
      save_mesh: 1
      n_epochs_opt: 250
      debug_n_save: 1
      save_render: 1
      save_acc_heatmap: 0
      new_frame_period: 5

      lr: &DEFAULT_lr
        stretching: 5e1   #5e1
        shearing: 1e-1    #1e-1
        bending: 1e-2     #1e-2
        external: 5e-2    #5e-2
        vertex: 1e-3      #1e-3
        uv: 2e-4          #2e-4

      lc: &DEFAULT_lc  # loss coefficients
        rgb: 1
        sil: 1
        shift: 1e-2

    rollout: &DEFAULT_ROLLOUT
      n_frames: 600
      save_render: 1
      save_acc_heatmap: 1
      save_render_metamizer: 0
      json: [ "sft/scenes/S1_res100.json" ]

a: &a
  <<: *DEFAULT
  name: '0426_01_mgnn_a'
  net:
    <<: *DEFAULT_NET
    message_passing_steps: 15
  inference: &inference_a
    <<: *DEFAULT_INFERENCE
    load_date_time: "??"
    postfix: "a"

b: &b
  <<: *DEFAULT
  name: '0428_01_mgnn_b'
  net:
    <<: *DEFAULT_NET
    message_passing_steps: 5
  inference: &inference_b
    <<: *DEFAULT_INFERENCE
    load_date_time: "2025-04-28 15:42:51"
    postfix: "b"

c: &c
  <<: *DEFAULT
  name: '0428_02_mgnn_c'
  net:
    <<: *DEFAULT_NET
    message_passing_steps: 5
  inference: &inference_c
    <<: *DEFAULT_INFERENCE
    load_date_time: "2025-05-02 04:55:06"
    postfix: "c"

d: &d
  <<: *DEFAULT
  name: '0519_01_mgnn_d'
  net:
    <<: *DEFAULT_NET
    message_passing_steps: 15
  data:
    <<: *DEFAULT_DATA
    height: 32
    width: 32
  opt:
    <<: *DEFAULT_OPT
    batch_size: 10
  inference: &inference_d
    <<: *DEFAULT_INFERENCE
    load_date_time: "2025-05-19 16:32:14"
    postfix: "d"

e: &e
  <<: *DEFAULT
  name: '0519_02_mgnn_e'
  net:
    <<: *DEFAULT_NET
    message_passing_steps: 15
  data:
    <<: *DEFAULT_DATA
    height: 32
    width: 32
    n_batches_per_epoch: 5000
  opt:
    <<: *DEFAULT_OPT
    batch_size: 10
  inference: &inference_e
    <<: *DEFAULT_INFERENCE
    load_date_time: "??"
    postfix: "e"


f: &f
  <<: *DEFAULT
  name: '??'
  net:
    <<: *DEFAULT_NET
    message_passing_steps: 15
    node_input_size: 5

  data: &data_f
    <<: *DEFAULT_DATA
    height: 32
    width: 32
    n_batches_per_epoch: 5000
  opt:
    <<: *DEFAULT_OPT
    batch_size: 10
  inference: &inference_f
    <<: *DEFAULT_INFERENCE
    load_date_time: "??"
    postfix: "e"


test: &test
  <<: *DEFAULT
  name: 'mgn_test'
  net:
    <<: *DEFAULT_NET
  data:
    <<: *DEFAULT_DATA
    dataset_size: 60
    n_batches_per_epoch: 5000  # default is 5000 or 501?
  cloth:
    <<: *DEFAULT_CLOTH
  opt:
    <<: *DEFAULT_OPT
    n_epochs: 100
  inference: &inference_test
    <<: *DEFAULT_INFERENCE
    load_date_time: ""
    postfix: "test"




################################################
local:
  <<: *f
  opt:
    <<: *DEFAULT_OPT
    batch_size: 3
    cuda: 0
    plot: 0
    i_save: 1

  data:
    <<: *data_f
    dataset_size: 5000
    height: 32
    width: 32

  # Weights and biases
  wandb:
    <<: *DEFAULT_WANDB
    log: false

  inference:
    <<: *inference_b
    renderer: "PyTorch3D"
    sft:
      <<: *DEFAULT_SFT
      json: ["sft/scenes/S1_res32.json"]
      evaluate: 0
      optimize_uv: 0
      debug: 1
    cuda: 0




debug: &debug
  <<: *d
  opt:
    <<: *DEFAULT_OPT
    batch_size: 20

  wandb:
    <<: *DEFAULT_WANDB
    log: false


