default: &DEFAULT
  name: 'metamizer_base'
  net:
    name: 'Metamizer'
    SMP_model_type: Unet
    SMP_encoder_name: resnet34
    hidden_size: 20
    symmetry_group: D4
    dtype: float64


  ema:
    update_after_step: None  # Start updating EMA after this number of steps
    update_every: 1  # Update EMA every 'n' steps
    beta: 0.995  # EMA smoothing factor (closer to 1 means smoother updates)

  data: &DEFAULT_DATA
    dataset_size: 1000
    average_sequence_length: 1000
    n_batches_per_epoch: 5000  # default is 5000 or 501?

    height: 100
    width: 100
    seed: 666

    use_cloth: 1
    use_fluid: 1
    use_diffusion: 1
    use_poisson: 1

  # Optimizer
  opt: &DEFAULT_OPT
    lr: 0.001  # Learning rate for the optimizer
    batch_size: 10  # Batch size for training
    n_epochs: 100  # Number of training epochs
    clip_grad_norm: null  # Gradient norm clipping threshold
    clip_grad_value: null  # Gradient value clipping threshold
    cuda: 1
    plot: 0
    save_mesh: 1
    i_save: 1
    L_shear_bend_version: 1
    seed: 666
    optimizer: adamw


  cloth: &DEFAULT_CLOTH
    use_f_ext: 0
    max_stretching: 1000  # Maximum stretching parameter for cloth
    min_stretching: 100  # Minimum stretching parameter for cloth
    max_shearing: 100  # Maximum shearing parameter for cloth
    min_shearing: 1  # Minimum shearing parameter for cloth
    max_bending: 10  # Maximum bending parameter for cloth
    min_bending: 0.01  # Minimum bending parameter for cloth
    repulsive: &DEFAULT_repulsive
      k: 0
      resolution: 32  # Repulsive force between cloth vertices

    a_ext: 1  # External acceleration (gravitational constant)
    min_a_ext: null  # Minimum gravitational constant (defaults to a_ext if not set)
    g: 0.125  # Gravitational constant (deprecated, prefer a_ext)
    L_0: 1  # Rest length of cloth grid edges
    dt: 1  # Timestep for cloth simulation integrator
#    f_ext_percentage: 0.2

    # Load parameters
    l_stretching: null  # Load stretching parameter of cloth
    l_shearing: null  # Load shearing parameter of cloth
    l_bending: null  # Load bending parameter of cloth
    l_g: null  # Load gravitational constant
    l_L_0: null  # Load rest length of cloth grid edges
    l_dt: 1  # Load timestep of cloth simulation integrator
    load_date_time: null  # Date and time of the run to load
    load_index: null  # Index of the run to load
    load_optimizer: false  # Whether to load the state of the optimizer
    load_latest: false  # Load the latest version for training (overrides date_time and index)

  Fluid: &DEFAULT_FLUID
    integrator: imex
    loss_bound: 20
    loss_nav: 1
    loss_mean_a: 0.1
    loss_mean_p: 0.1
    regularize_grad_p: 0
    max_speed: 0
    mu: 10
    min_mu: 0.01
    rho: 10
    min_rho: 0.01

  Diffusion: &DEFAULT_DIFFUSION
    D: 1000
    min_D: 1

  Wave: &DEFAULT_WAVE
    c: 10
    min_c: 0.1

  # Weights and biases
  wandb: &DEFAULT_WANDB
    root_dir: './'
    log: true
    group: 'metamizer'

  distributed:
    use_distributed: False
    wireup_info: 'mpi'
    wireup_store: 'tcp'
    model_parallel_size: 1

  inference: &DEFAULT_INFERENCE
    load_date_time: "2024-09-25 03:02:43"
    load_index: null
    save_obj: 0
    visualize_scaling: 0
    visualize_grads: 0
    postfix: "a"
    renderer: "Nvdiffrast"          # Nvdiffrast / PyTorch3D
    framerate: 30
    average_sequence_length: 100
    iterations_per_timestep: 3
    height: 100
    width: 100
    cuda: 1
    material:
      stretching: 1000
      shearing: 10
      bending: 10
    sft: &DEFAULT_SFT
#      json: [ "scenes/R1.json", "scenes/R2.json","scenes/R3.json","scenes/R4.json","scenes/R5.json","scenes/R6.json","scenes/R7.json","scenes/R8.json","scenes/R9.json","scenes/S1_res32.json","scenes/S2_res32.json","scenes/S3_res32.json","scenes/S4_res32.json" ]
#      json: ["sft/scenes/S1_res32.json", "scenes/S2_res32.json", "scenes/S3_res32.json", "scenes/S4_res32.json"]
      json: ["sft/scenes/S1_res100.json"]
#      json: ["scenes/R1.json"]
      evaluate: 1
      optimize_uv: 0
      debug: 1
      save_mesh: 1
      n_epochs_opt: 250
      debug_n_save: 1
      save_render: 1
      save_acc_heatmap: 0
      new_frame_period: 10  # 5

      lr: &DEFAULT_lr
        stretching: 5e1   # 5e1
        shearing: 1e-1    # 1e-1
        bending: 1e-2     # 1e-2
        external: 1       # 5e-2
        vertex: 1e-2      # 1e-3
        uv: 2e-4          # 2e-4

      lc: &DEFAULT_lc  # loss coefficients
        rgb: 1
        sil: 1
        shift: 1e-2
        uv_smooth: 0

    rollout: &DEFAULT_ROLLOUT
      n_frames: 300
      save_render: 1
      save_acc_heatmap: 1
      json: ["sft/scenes/S1_res32.json"]


author_ckpt1: &author_ckpt1
  <<: *DEFAULT
  name: '0320_01'
  opt:
    <<: *DEFAULT_OPT
    cuda: 1
    plot: 0
  cloth:
    <<: *DEFAULT_CLOTH

  inference: &inference_author_ckpt1
    <<: *DEFAULT_INFERENCE
    load_date_time: "2024-09-25 03:02:43"
    height: 100
    width: 100
    visualize_scaling: 0
    visualize_grads: 0
    iterations_per_timestep: 10
    postfix: "author1"



author_ckpt2: &author_ckpt2   # for laplace
  <<: *DEFAULT
  name: '0320_01'
  opt:
    <<: *DEFAULT_OPT
    cuda: 1
    plot: 0
  cloth:
    <<: *DEFAULT_CLOTH

  inference:
    <<: *DEFAULT_INFERENCE
    load_date_time: "2024-09-23 09:01:08"
    postfix: "author2"


a1: &a1
  <<: *DEFAULT
  name: '0320_02_cloth'
  opt:
    <<: *DEFAULT_OPT
    cuda: 1
    plot: 0
  cloth:
    <<: *DEFAULT_CLOTH

  inference:
    <<: *DEFAULT_INFERENCE
    load_date_time: "2025-03-20 10:59:22"
    postfix: "a1"


  data:
    <<: *DEFAULT_DATA
    use_cloth: 1
    use_fluid: 0
    use_diffusion: 0
    use_poisson: 0

a2: &a2
  <<: *DEFAULT
  name: '???'
  opt:
    <<: *DEFAULT_OPT
    cuda: 1
    plot: 0
  cloth:
    <<: *DEFAULT_CLOTH

  inference:
    <<: *DEFAULT_INFERENCE
    load_date_time: "2025-03-20 10:34:06"
    postfix: "a2"




a: &a
  <<: *DEFAULT
  name: '0321_01_fno'
  opt:
    <<: *DEFAULT_OPT
    cuda: 1
    plot: 0
    batch_size: 10
  cloth:
    <<: *DEFAULT_CLOTH
    use_f_ext: 1
  data:
    <<: *DEFAULT_DATA
    use_cloth: 1
    use_fluid: 0
    use_diffusion: 0
    use_poisson: 0

  inference:
    <<: *DEFAULT_INFERENCE
    load_date_time: "2025-03-21 18:59:41"
    postfix: "a"



b: &b
  <<: *DEFAULT
  name: '0320_06_all_ext'
  opt:
    <<: *DEFAULT_OPT
    cuda: 1
    plot: 0
    batch_size: 10
  cloth:
    <<: *DEFAULT_CLOTH
    use_f_ext: 1
  data:
    <<: *DEFAULT_DATA
    use_cloth: 1
    use_fluid: 1
    use_diffusion: 1
    use_poisson: 1
  inference:
    <<: *DEFAULT_INFERENCE
    load_date_time: "??"
    postfix: "b"


c: &c
  <<: *DEFAULT
  name: '0321_01_cloth_ext'
  opt:
    <<: *DEFAULT_OPT
    cuda: 1
    plot: 0
    batch_size: 10
  cloth:
    <<: *DEFAULT_CLOTH
    use_f_ext: 1
  data:
    <<: *DEFAULT_DATA
    use_cloth: 1
    use_fluid: 0
    use_diffusion: 0
    use_poisson: 0

  inference:
    <<: *DEFAULT_INFERENCE
    load_date_time: "2025-03-21 09:25:53"
    postfix: "c"


d: &d
  <<: *DEFAULT
  name: '0321_02_cloth_bs10'
  opt:
    <<: *DEFAULT_OPT
    cuda: 1
    plot: 0
    batch_size: 10
  cloth:
    <<: *DEFAULT_CLOTH
    use_f_ext: 0
  data:
    <<: *DEFAULT_DATA
    use_cloth: 1
    use_fluid: 0
    use_diffusion: 0
    use_poisson: 0
  inference:
    <<: *DEFAULT_INFERENCE
    load_date_time: "2025-03-21 09:28:02"
    postfix: "d"



e: &e
  <<: *DEFAULT
  name: '0322_01_cloth_bs10'
  opt:
    <<: *DEFAULT_OPT
    cuda: 1
    plot: 0
    batch_size: 10
  cloth:
    <<: *DEFAULT_CLOTH
    use_f_ext: 0
  data:
    <<: *DEFAULT_DATA
    use_cloth: 1
    use_fluid: 0
    use_diffusion: 0
    use_poisson: 0
  inference:
    <<: *DEFAULT_INFERENCE
    load_date_time: "2025-03-22 23:21:22"
    postfix: "e"

f: &f   # OK
  <<: *DEFAULT
  name: '0325_06_cloth_bs10'
  opt:
    <<: *DEFAULT_OPT
    cuda: 1
    plot: 0
    batch_size: 10
  cloth:
    <<: *DEFAULT_CLOTH
    use_f_ext: 0
  data:
    <<: *DEFAULT_DATA
    use_cloth: 1
    use_fluid: 0
    use_diffusion: 0
    use_poisson: 0
  inference: &inference_f
    <<: *DEFAULT_INFERENCE
    load_date_time: "2025-03-25 14:31:45"
    height: 100
    width: 100
    postfix: "f"

f2:
  <<: *f
  name: '0424_01_cloth'
  inference:
    <<: *DEFAULT_INFERENCE
    load_date_time: "??"
    height: 100
    width: 100
    postfix: "f2"

f3:
  <<: *f
  name: '0424_02_cloth_ext'
  cloth:
    <<: *DEFAULT_CLOTH
    use_f_ext: 1

  inference:
    <<: *DEFAULT_INFERENCE
    load_date_time: "??"
    height: 100
    width: 100
    postfix: "f3"

f4:
  <<: *f
  name: '0424_03_cloth_res32'
  inference:
    <<: *DEFAULT_INFERENCE
    load_date_time: "??"
    height: 32
    width: 32
    postfix: "f4"


h: &h
  <<: *DEFAULT
  name: '0326_02_cloth_repulsive'
  opt:
    <<: *DEFAULT_OPT
    batch_size: 10
  cloth:
    <<: *DEFAULT_CLOTH
    k_repulsive: 1000

  inference:
    <<: *DEFAULT_INFERENCE
    load_date_time: "2025-03-26 18:42:07"
    height: 32
    width: 32
    postfix: "h"

  data:
    <<: *DEFAULT_DATA
    use_cloth: 1
    use_fluid: 0
    use_diffusion: 0
    use_poisson: 0
    height: 32
    width: 32


i: &i
  <<: *DEFAULT
  name: '0326_03_cloth_repulsive'
  opt:
    <<: *DEFAULT_OPT
    batch_size: 10
  cloth:
    <<: *DEFAULT_CLOTH
    k_repulsive: 10

  inference:
    <<: *DEFAULT_INFERENCE
    load_date_time: "2025-03-26 18:43:21"
    height: 32
    width: 32
    postfix: "i"

  data:
    <<: *DEFAULT_DATA
    use_cloth: 1
    use_fluid: 0
    use_diffusion: 0
    use_poisson: 0
    height: 32
    width: 32


j: &j
  <<: *DEFAULT
  name: '0402_01_cloth_bs10'
  opt:
    <<: *DEFAULT_OPT
    cuda: 1
    plot: 0
    batch_size: 10
  cloth:
    <<: *DEFAULT_CLOTH
    use_f_ext: 0
  data:
    <<: *DEFAULT_DATA
    use_cloth: 1
    use_fluid: 0
    use_diffusion: 0
    use_poisson: 0
  inference:
    <<: *DEFAULT_INFERENCE
    load_date_time: "2025-04-02 18:35:36"
    postfix: "j"
#    visualize_grads: 1
#    visualize_scaling: 1

k: &k
  <<: *DEFAULT
  name: '0403_01_cloth_bs10'
  opt:
    <<: *DEFAULT_OPT
    cuda: 1
    plot: 0
    batch_size: 10
  cloth:
    <<: *DEFAULT_CLOTH
    use_f_ext: 0
    g: 1    # use g=1 (original value)
  data:
    <<: *DEFAULT_DATA
    use_cloth: 1
    use_fluid: 0
    use_diffusion: 0
    use_poisson: 0

  inference:
    <<: *DEFAULT_INFERENCE
    load_date_time: "2025-04-02 18:35:36"
    postfix: "k"
#    visualize_grads: 1
#    visualize_scaling: 1



rep_a: &rep_a
  <<: *DEFAULT
  name: '0326_04_cloth_repulsive'
  opt:
    <<: *DEFAULT_OPT
    batch_size: 10
  cloth:
    <<: *DEFAULT_CLOTH
    k_repulsive: 0.001

  inference:
    <<: *DEFAULT_INFERENCE
    load_date_time: "2025-03-26 22:38:26"
    height: 32
    width: 32
    postfix: "rep_a"

  data:
    <<: *DEFAULT_DATA
    use_cloth: 1
    use_fluid: 0
    use_diffusion: 0
    use_poisson: 0
    height: 32
    width: 32

rep_b: &rep_b
  <<: *DEFAULT
  name: '0326_05_cloth_repulsive'
  opt:
    <<: *DEFAULT_OPT
    batch_size: 10
  cloth:
    <<: *DEFAULT_CLOTH
    k_repulsive: 0.00001

  inference:
    <<: *DEFAULT_INFERENCE
    load_date_time: "2025-03-26 23:13:40"
    height: 32
    width: 32
    postfix: "rep_b"

  data:
    <<: *DEFAULT_DATA
    use_cloth: 1
    use_fluid: 0
    use_diffusion: 0
    use_poisson: 0
    height: 32
    width: 32

rep_c: &rep_c # OOM
  <<: *DEFAULT
  name: '0327_01_cloth_repulsive'
  opt:
    <<: *DEFAULT_OPT
    batch_size: 1
  cloth:
    <<: *DEFAULT_CLOTH
    repulsive:
      k: 1e-7
      resolution: 100

  data:
    <<: *DEFAULT_DATA
    use_cloth: 1
    use_fluid: 0
    use_diffusion: 0
    use_poisson: 0
    height: 100
    width: 100
  inference:
    <<: *DEFAULT_INFERENCE
    load_date_time: "??"
    height: 100
    width: 100
    postfix: "rep_c"


rep_d: &rep_d
  <<: *DEFAULT
  name: '0327_02_cloth_repulsive'
  opt:
    <<: *DEFAULT_OPT
    batch_size: 10
  cloth:
    <<: *DEFAULT_CLOTH
    repulsive:
      k: 1e-7
      resolution: 32
  data:
    <<: *DEFAULT_DATA
    use_cloth: 1
    use_fluid: 0
    use_diffusion: 0
    use_poisson: 0
    height: 100
    width: 100
  inference:
    <<: *DEFAULT_INFERENCE
    load_date_time: "2025-03-27 23:39:53"
    height: 100
    width: 100
    postfix: "rep_d"

rep_e: &rep_e
  <<: *DEFAULT
  name: '0327_03_cloth_repulsive'
  opt:
    <<: *DEFAULT_OPT
    batch_size: 10
  cloth:
    <<: *DEFAULT_CLOTH
    repulsive:
      k: 1e-9
      resolution: 32
  data:
    <<: *DEFAULT_DATA
    use_cloth: 1
    use_fluid: 0
    use_diffusion: 0
    use_poisson: 0
    height: 100
    width: 100
  inference:
    <<: *DEFAULT_INFERENCE
    load_date_time: "2025-03-27 23:40:51"
    height: 100
    width: 100
    postfix: "rep_e"

rep_f: &rep_f
  <<: *DEFAULT
  name: '0328_01_cloth_repulsive'
  opt:
    <<: *DEFAULT_OPT
    batch_size: 10
  cloth:
    <<: *DEFAULT_CLOTH
    repulsive:
      k: 1e-5
      resolution: 32
  data:
    <<: *DEFAULT_DATA
    use_cloth: 1
    use_fluid: 0
    use_diffusion: 0
    use_poisson: 0
    height: 100
    width: 100
  inference:
    <<: *DEFAULT_INFERENCE
    load_date_time: "2025-03-28 19:23:20"
    height: 100
    width: 100
    postfix: "rep_f"


rep_g: &rep_g
  <<: *DEFAULT
  name: '0328_02_cloth_repulsive'
  opt:
    <<: *DEFAULT_OPT
    batch_size: 10
  cloth:
    <<: *DEFAULT_CLOTH
    repulsive:
      k: 1e-6
      resolution: 32
  data:
    <<: *DEFAULT_DATA
    use_cloth: 1
    use_fluid: 0
    use_diffusion: 0
    use_poisson: 0
    height: 100
    width: 100
  inference:
    <<: *DEFAULT_INFERENCE
    load_date_time: "2025-03-28 19:29:16"
    height: 100
    width: 100
    postfix: "rep_g"


rep3_a: &rep3_a
  <<: *DEFAULT
  name: '0331_05_cloth_repul_new'
  opt:
    <<: *DEFAULT_OPT
    batch_size: 10
    clip_grad_norm: 1
  cloth:
    <<: *DEFAULT_CLOTH
    repulsive:
      k: 1
      resolution: 32

  inference:
    <<: *DEFAULT_INFERENCE
    load_date_time: "2025-03-31 16:35:11"
    height: 32
    width: 32
    postfix: "rep3_a"

  data:
    <<: *DEFAULT_DATA
    use_cloth: 1
    use_fluid: 0
    use_diffusion: 0
    use_poisson: 0
    height: 100
    width: 100

rep3_b: &rep3_b
  <<: *rep3_a
  name: '0331_06_cloth_repul_new'
  opt:
    <<: *DEFAULT_OPT
    batch_size: 10
    clip_grad_norm: null
  cloth:
    <<: *DEFAULT_CLOTH
    repulsive:
      k: 1e-2
      resolution: 32
  inference:
    <<: *DEFAULT_INFERENCE
    load_date_time: "2025-03-31 16:35:44"
    postfix: "rep3_b"


rep3_c: &rep3_c
  <<: *rep3_a
  name: '0331_07_cloth_repul_new'
  opt:
    <<: *DEFAULT_OPT
    batch_size: 10
    clip_grad_norm: null
  cloth:
    <<: *DEFAULT_CLOTH
    repulsive:
      k: 1e-4
      resolution: 32
  inference:
    <<: *DEFAULT_INFERENCE
    load_date_time: "2025-03-31 16:35:48"
    postfix: "rep3_c"

rep3_d: &rep3_d
  <<: *rep3_a
  name: '0331_08_cloth_repul_new'
  opt:
    <<: *DEFAULT_OPT
    batch_size: 10
    clip_grad_norm: 1
  cloth:
    <<: *DEFAULT_CLOTH
    repulsive:
      k: 1
      resolution: 32
  inference:
    <<: *DEFAULT_INFERENCE
    load_date_time: "2025-03-31 16:52:31"
    postfix: "rep3_d"

rep3_e: &rep3_e
  <<: *rep3_a
  name: '0331_09_cloth_repul_new'
  opt:
    <<: *DEFAULT_OPT
    batch_size: 10
    clip_grad_norm: 1
  cloth:
    <<: *DEFAULT_CLOTH
    repulsive:
      k: 1e-2
      resolution: 32
  inference:
    <<: *DEFAULT_INFERENCE
    load_date_time: "2025-03-31 16:52:50"
    postfix: "rep3_e"

rep3_f: &rep3_f
  <<: *rep3_a
  name: '0331_10_cloth_repul_new'
  opt:
    <<: *DEFAULT_OPT
    batch_size: 10
    clip_grad_norm: 1
  cloth:
    <<: *DEFAULT_CLOTH
    repulsive:
      k: 1e-4
      resolution: 32
  inference:
    <<: *DEFAULT_INFERENCE
    load_date_time: "2025-03-31 16:52:44"
    iterations_per_timestep: 50
    postfix: "rep3_f"


rep3_g: &rep3_g
  <<: *rep3_a
  name: '0331_11_cloth_repul_new'
  opt:
    <<: *DEFAULT_OPT
    batch_size: 10
    clip_grad_norm: 1
  cloth:
    <<: *DEFAULT_CLOTH
    repulsive:
      k: 1e-6
      resolution: 32
  inference:
    <<: *DEFAULT_INFERENCE
    load_date_time: "2025-03-31 17:08:11"
    save_obj: 1
    postfix: "rep3_g"


rep3_h: &rep3_h
  <<: *rep3_a
  name: '0331_12_cloth_repul_new'
  opt:
    <<: *DEFAULT_OPT
    batch_size: 10
    clip_grad_norm: 1
  cloth:
    <<: *DEFAULT_CLOTH
    repulsive:
      k: 1e-8
      resolution: 32
  inference:
    <<: *DEFAULT_INFERENCE
    load_date_time: "2025-03-31 17:08:42"
    iterations_per_timestep: 50
    visualize_scaling: 1
    visualize_grads: 1
    postfix: "rep3_h"


rep3_i: &rep3_i
  <<: *rep3_a
  name: '0331_13_cloth_repul_new'
  opt:
    <<: *DEFAULT_OPT
    batch_size: 10
    clip_grad_norm: 1
  cloth:
    <<: *DEFAULT_CLOTH
    repulsive:
      k: 1e-10
      resolution: 32
  inference:
    <<: *DEFAULT_INFERENCE
    load_date_time: "2025-03-31 17:09:04"
    save_obj: 1
    iterations_per_timestep: 50
    postfix: "rep3_i"



rep3_j: &rep3_j
  <<: *rep3_a
  name: '0331_14_cloth_repul_new'
  opt:
    <<: *DEFAULT_OPT
    batch_size: 10
    clip_grad_norm: 1
  cloth:
    <<: *DEFAULT_CLOTH
    repulsive:
      k: 1e-12
      resolution: 32
  inference:
    <<: *DEFAULT_INFERENCE
    load_date_time: "2025-03-31 17:09:04"
    save_obj: 1
    postfix: "rep3_j"


rep4_a: &rep4_a
  <<: *DEFAULT
  name: '0331_15_cloth_repul_new'
  opt:
    <<: *DEFAULT_OPT
    batch_size: 10
    clip_grad_norm: 1
  cloth:
    <<: *DEFAULT_CLOTH
    repulsive:
      k: 1e-8
      resolution: 32

  inference:
    <<: *DEFAULT_INFERENCE
    load_date_time: "2025-04-01 01:54:39"
    height: 100
    width: 100
    postfix: "rep4_a"

  data:
    <<: *DEFAULT_DATA
    use_cloth: 1
    use_fluid: 0
    use_diffusion: 0
    use_poisson: 0
    height: 100
    width: 100


rep4_b: &rep4_b
  <<: *rep4_a
  name: '0331_16_cloth_repul_new'
  opt:
    <<: *DEFAULT_OPT
    batch_size: 10
    clip_grad_norm: 1
  cloth:
    <<: *DEFAULT_CLOTH
    repulsive:
      k: 1e-6
      resolution: 32
  inference:
    <<: *DEFAULT_INFERENCE
    load_date_time: "2025-04-01 01:54:39"
    postfix: "rep4_b"


rep4_c: &rep4_c
  <<: *rep4_a
  name: '0402_02_cloth_repul'
  opt:
    <<: *DEFAULT_OPT
    batch_size: 10
    clip_grad_norm: 1
  cloth:
    <<: *DEFAULT_CLOTH
    repulsive:
      k: 1e-10
      resolution: 32 
  inference:
    <<: *DEFAULT_INFERENCE
    load_date_time: "2025-04-02 22:07:11"
    postfix: "rep4_c"



################################################
local:
  <<: *f
  opt:
    <<: *DEFAULT_OPT
    batch_size: 3
    cuda: 0
    plot: 0


  data:
    <<: *DEFAULT_DATA
    dataset_size: 5000
    use_cloth: 1
    use_fluid: 0
    use_diffusion: 0
    use_poisson: 0
    height: 32
    width: 32

  # Weights and biases
  wandb:
    <<: *DEFAULT_WANDB
    log: false

  inference:
    <<: *inference_author_ckpt1
    renderer: "PyTorch3D"
    sft:
      <<: *DEFAULT_SFT
      json: ["sft/scenes/S1_res32_debug.json"]
      evaluate: 0
      optimize_uv: 0
      debug: 1
    cuda: 0


debug:
  <<: *rep_d
  # Weights and biases
  wandb:
    <<: *DEFAULT_WANDB
    log: false


